### ISSUE TITLE
Cloud Server API

### ISSUE THREAD

**Issue by james-hanks** [OHIF/Viewers#3490]
- [x] #3542 
- [x] #3230 
- [x] #3554 
- [ ] #3555

**Comment by james-hanks** [comment]
#3230

**Comment by jbocce** [comment]
```[tasklist]
### Tasks for this Epic
- [ ] https://github.com/OHIF/Viewers/issues/3542
- [ ] https://github.com/OHIF/Viewers/issues/3230
- [ ] Create generic interface to fetch the contents of the various 'buckets' from the cloud server
- [ ] Create the API as is defined in the Epic description above
```

**Comment by james-hanks** [comment]
#3543 PR
